name: fre-cli
channels:
  - defaults
  - conda-forge
  - noaa-gfdl
dependencies:
  - python
  - click
  - pyyaml
  - pylint
  - jsonschema
  - noaa-gfdl::intakebuilder
  - conda-forge::cylc-flow
  - conda-forge::cylc-rose
  - conda-forge::metomi-rose
  - conda-forge::cmor