{% set data = load_setup_py_data() %}

package:
  name: fre-cli
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/NOAA-GFDL/fre-cli
  path: .

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

channels:
    - defaults
    - conda-forge
    - noaa-gfdl

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - pyyaml
    - jsonschema
    - noaa-gfdl::intakebuilder
    - conda-forge::metomi-rose

test:
  imports:
    - click
    - fre
    - fre.frepp
    - fre.frepp.install
    - fre.frepp.status
    - fre.frepp.run
    - fre.frepp.validate
    # next line should import but it does not due to mystery
    #- fre.freapp
  commands:
    - fre --help
    - fre pp --help
    - fre pp install --help
    - fre pp status --help
    - fre pp run --help
    - fre pp validate --help
    - fre app --help
    - fre app mask-atmos-plevel --help

about:
  home: https://github.com/NOAA-GFDL/fre-cli
  license: LGPL-3.0
  license_file: LICENSE.md
  summary: Command line interface for FMS Runtime Environment (FRE) workflow commands
  author: Bennett Chang, Dana Singh, Chris Blanton
