{% set data = load_setup_py_data() %}

package:
  name: fre-cli
  version: {{ data.get('version') }}

source:
  path: .
# ideally we would want to have this git_url path, but it messes with the conda publish workflow, where it builds only the sourced url and not local/branch changes
# git_url: https://github.com/NOAA-GFDL/fre-cli

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

channels:
    - defaults
    - conda-forge
    - noaa-gfdl

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - pyyaml
    - jsonschema
    - noaa-gfdl::intakebuilder
    - conda-forge::cylc-flow
    - conda-forge::cylc-rose
    - conda-forge::metomi-rose
    - conda-forge::cmor

test:
  imports:
    - click
    - fre
    - fre.pp
    - fre.pp.install
    - fre.pp.status
    - fre.pp.run
    - fre.pp.validate
    - fre.app
    - fre.cmor
  commands:
    - fre --help
    - fre pp --help
    - fre pp install --help
    - fre pp status --help
    - fre pp run --help
    - fre pp validate --help
    - fre app --help
    - fre app mask-atmos-plevel --help
    - fre cmor --help
    - fre cmor run --help

about:
  home: https://github.com/NOAA-GFDL/fre-cli
  license: LGPL-3.0
  license_file: LICENSE.md
  summary: Command line interface for FMS Runtime Environment (FRE) workflow commands
  author: Bennett Chang, Dana Singh, Chris Blanton
