package:
  name: fre-cli
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

source:
  # url: https://github.com/NOAA-GFDL/fre-cli
  path: .

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

channels:
    - defaults
    - conda-forge
    - noaa-gfdl

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - pyyaml
    - jsonschema
    - noaa-gfdl::intakebuilder
    - conda-forge::metomi-rose

test:
  imports:
    - click
    - fre

about:
  home: https://github.com/NOAA-GFDL/fre-cli
  license: LGPL-3.0
  license_file: LICENSE.md
  summary: Command line interface for FMS Runtime Environment (FRE) workflow commands
  author: Bennett Chang, Dana Singh, Chris Blanton
