name: build_conda
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/fre-cli:miniconda24.7.1_gcc14.2.0
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
      - name: Run Conda to Build
        run: |
          conda config --append channels conda-forge
          conda config --append channels noaa-gfdl
          conda install conda-build conda-verify
          conda build .
