name: build_conda
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v4
    - name: Get Version from Git Tag
      run: |
        # Capture the output of the git command and store in a variable
        version=$(git describe --abbrev=0 --tags 2> /dev/null)
        # Check if the command was successful (exit code 0)
        if [[ $? -eq 0 ]]; then
          echo "Version retrieved from git tag: $version"
          # Export the version as an environment variable
          export CONDA_PACKAGE_VERSION=$version
        else
          echo "Error: Could not retrieve version from git tag."
          # Exit the workflow with an error code (optional)
          exit 1
        fi 
    - name: Run Docker to Build
      run: |
        conda config --append channels conda-forge
        conda config --append channels noaa-gfdl
        conda install conda-build conda-verify
        conda build --version ${{ env.CONDA_PACKAGE_VERSION }} .
    - name: Pylint All Code
      continue-on-error: true
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pylint --clear-cache-post-run y ./fre
