name: change_version
on:
  push:
    branches:
      - main
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Read current version
      id: read_version
      run: echo "::set-output name=version::$(cat version.txt)"
    - name: Increment version
      id: increment_version
      run: echo "::set-output name=version::$(echo "${{ steps.read_version.outputs.version }} + 0.0.1" | bc)"
    - name: Update version file
      run: echo "${{ steps.increment_version.outputs.version }}" > version.txt
    - name: Commit version increment
      run: |
        git config --global user.name 'Bennett Chang'
        git config --global user.email 'bcc2761@g.rit.edu'
        git add version.txt
        git commit -m "Increment version"
        git push