name: create_test_conda_env

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '>=3.9'

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Create fre-cli environment
      run: |
        # create environment catalogbuilder will be installed into
        conda env create -f environment.yml --name fre-cli
        # install fre-cli
        $CONDA/envs/fre-cli/bin/python -m pip install .

    - name: Run pytest in catalogbuilder environment
      run: |
        which python
        python --version
        $CONDA/envs/fre-cli/bin/python --version
        # which pytest
        $CONDA/envs/fre-cli/bin/pytest
