name: documentation

on: [push]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx renku-sphinx-theme sphinx-rtd-theme          
          pip install --upgrade sphinx-rtd-theme
      - name: Sphinx build
        run: |
          # list content of docs dir before spinx-apidoc
          ls docs/
          # generate .rst from doc strings in fre/ modules
          sphinx-apidoc --output-dir docs fre/ --separate          
          # list content of docs dir after spinx-apidoc
          ls docs/
          # build content in docs/ dir, target is build/ dir
          sphinx-build docs build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true
