name: publish_conda
on:
  push:
    branches:
    - main
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Run Docker to Build and Upload
      run: |
        conda config --append channels conda-forge
        # conda config --append channels chris.blanton
        # conda config --append channels noaa-gfdl
        conda config --append channels bcc2761
        conda install conda-build anaconda-client
        export ANACONDA_API_TOKEN=bc-20e9ae2b-3e1c-4bd2-9fb3-c40debed12c8
        # anaconda -t bc-20e9ae2b-3e1c-4bd2-9fb3-c40debed12c8 login
        # anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
        conda config --set anaconda_upload yes
        conda build .
