name: publish_conda

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        AnacondaToken: ${{ secrets.CLI_ANACONDA_TOKEN }}
        platforms: 'all'
        override: true
        dry_run: true
