name: publish_conda
on:
  push:
    branches:
    - main
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Run Docker to Build and Upload
      run: |
        conda install conda-build anaconda-client
        conda install conda-forge::intake-esm
        anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
        conda config --set anaconda_upload yes
        conda build .
